version: '3'

  #tasks:
  #build:
  #	cmds:
  #   - odin build testbed -out:bin/testbed -o:debug 
  #  generates:
  #    - bin/testbed
  #	sources:
  #	  - testbed/**/*.odin
  #	method: none
  #	silent: true

tasks:
  build:
    cmds:
     - odin build src -out:bin/vodin -o:none -strict-style -debug
    generates:
      - bin/vodin
    sources: 
      - src/**/*.odin    
    method: none
    silent: true  
